name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/sublime-sunspot-420109/subtitle-generator:latest

    - name: Install Google Cloud SDK
      run: |
        echo "Installing Google Cloud SDK..."
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_KEY }}" > "${HOME}/gcloud-service-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
        gcloud config set project sublime-sunspot-420109

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy subtitle-service \
          --image gcr.io/sublime-sunspot-420109/subtitle-generator:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 1Gi

