name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or any other branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gcr.io/sublime-sunspot-420109/your-app-name:latest
        file: ./Dockerfile
        context: .

    - name: Log out from Google Container Registry
      run: docker logout gcr.io
